export enum ActionType {
    ADD_HABBAJET = 'Add Habbajet',
    ADD_HABIT_RESULT = 'Add Habit Result',
    UPDATE_BUDGET = 'Update Budget',
    RESET_HABBAJET = 'Reset Habbajet',
    LOAD_STATE = 'Load State',
    SELECT_HABBAJET = 'Select Habbajet',
    UPDATE_EDITOR_FIELD = 'Update Editor Field',
    VALIDATE_EDITOR = 'Validate Editor',
    CLEAR_EDITOR = 'Clear Editor',
    ADD_PURCHASE = 'Add Purchase',
    UPDATE_PURCHASE_EDITOR = 'Update Purchase Editor',
    CLEAR_PURCHASE_EDITOR = 'Clear Purchase Editor',
    VALIDATE_PURCHASE_EDITOR = 'Validate Purchase Editor',
    SET_HABBAJET_TO_EDIT = 'Set Habbajet To Edit',
    DELETE_HABBAJET = 'Delete Habbajet',
    ADD_TAG = 'Add Tag',
    SET_PURCHASE_TO_EDIT = 'Set Purchase To Edit',
    SET_TAG_TO_EDIT = 'Set Tag To Edit',
    UPDATE_TAG_EDITOR = 'Update Tag Editor',
    CLEAR_TAG_EDITOR = 'Clear Tag Editor',
    VALIDATE_TAG_EDITOR = 'Validate Tag Editor',
    DELETE_TAG = 'Delete Tag',
}
